# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d4d9f8789d7197692cf792ee8279de87"
name = "bundle-discount-app"
#application_url = "https://example.com"
application_url = "https://bundle-discount-production-0ede.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts,read_discounts,read_products,write_metaobjects,write_metaobject_definitions"


[auth]
redirect_urls = [
  "https://bundle-discount-production-0ede.up.railway.app/auth/callback",
  "https://bundle-discount-production-0ede.up.railway.app/auth/shopify/callback",
  "https://bundle-discount-production-0ede.up.railway.app/api/auth"
]

[[extensions]]
type = "function"
name = "bundle-discount"
handle = "bundle-discount"
api_version = "2025-04"

  [[extensions.metafields]]
  namespace = "bundle-discount"
  key = "config"