# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0e915ab84426cd3946d9b90055aac443"
name = "bundle-discount-app"
#application_url = "https://example.com"
application_url = "https://dark-taxes-fry.loca.lt"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts,read_discounts,read_products,write_metaobjects,write_metaobject_definitions"


[auth]
redirect_urls = [ "https://dark-taxes-fry.loca.lt/auth/callback",
                  "https://dark-taxes-fry.loca.lt/auth/shopify/callback",
                  "https://dark-taxes-fry.loca.lt/api/auth" ]

[[extensions]]
type = "function"
name = "bundle-discount"
handle = "bundle-discount"
api_version = "2025-04"

  [[extensions.metafields]]
  namespace = "bundle-discount"
  key = "config"