api_version = "2026-04"

[[extensions]]
name = "bundle-discount"
handle = "bundle-discount"
type = "function"
uid = "208e9edf-8b9b-6b74-3f3a-539fdede2328f859a084"
description = "Bundle discount based on collection membership"

  [[extensions.targeting]]
  target = "purchase.order-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""  # ✅ actual build command
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"